### ISSUE TITLE
Error on prepareFire

### ISSUE THREAD

**Issue by jssosa10** [FLAGlab/DCoPN#1]
petrinode: line 215 => copy := *pn.remoteTransitionOptions[peerAddr][transition.ID]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6de5ce]

cause: peerAddress = itself remoteTransitions[peer] = empty map 

image:
![image](https://user-images.githubusercontent.com/15165524/55270680-eba7c900-526f-11e9-89da-5faeab7944c3.png)

**Comment by jdfandino10** [comment]
Fixed
